### ISSUE TITLE
Ruby version mismatch

### ISSUE THREAD

**Issue by minond** [hayderahmad/crypto#4]
The Ruby version specified in `Gemfile` and in `.ruby-version` don't match. This causes issues with a dev using rbenv or rvm runs this app since rbenv/rvm will make it so the Ruby specified in `.ruby-version` (v2.7.0) is used, but when you run `bundle install` you get an error from bundler saying that Ruby v3.1.2 is expected to be used.

The versions should either match or only specified in the `.ruby-version` file.

https://github.com/hayderahmad/crypto/blob/93f45379103450be99a788fe0758d8793a3f340e/Gemfile#L4

https://github.com/hayderahmad/crypto/blob/93f45379103450be99a788fe0758d8793a3f340e/.ruby-version#L1

**Comment by hayderahmad** [comment]
Thank you for pointing it out. I have fixed the issue in the following commit
https://github.com/hayderahmad/crypto/commit/dd6bd3a96c10898a1f645c75c2af072d75104404
