### ISSUE TITLE
Big controllers

### ISSUE THREAD

**Issue by minond** [hayderahmad/crypto#5]
The controllers do A LOT -- can that logic be moved into the models and/or other classes?

**Comment by hayderahmad** [comment]
Thank you for the feedback  the issue is tracked on this project
https://github.com/users/hayderahmad/projects/1/views/1

**Comment by minond** [comment]
Awesome. Looks like I don't have access to that project, but happy to see it's being worked on :)

Closing.

**Comment by hayderahmad** [comment]
Thank you for pointing that out. I just made the project public, so you should have read access.

**Comment by hayderahmad** [comment]
Hi Marcos
I am working on refactoring my code, and I did refactoring for a part of the code as in this commit
ff759bc1ba36b5bbbe82c80a41e42623bbf0c523
